######################################################################
# Automatically generated by qmake (3.0) Thu Mar 15 23:09:09 2018
######################################################################
QT += core gui widgets multimedia
TEMPLATE = app
TARGET = cis330_mainproject
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
RESOURCES += buttons.qrc images.qrc sounds.qrc
