#############################################################################
# Makefile for building: cis330_mainproject.app/Contents/MacOS/cis330_mainproject
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  cis330_mainproject.pro
# Template: app
# Command: /Users/halleking/anaconda/bin/qmake -o Makefile cis330_mainproject.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../anaconda/include/qt -I../anaconda/include/qt/QtWidgets -I../anaconda/include/qt/QtMultimedia -I../anaconda/include/qt/QtGui -I../anaconda/include/qt/QtNetwork -I../anaconda/include/qt/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../anaconda/mkspecs/macx-clang
QMAKE         = /Users/halleking/anaconda/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cis330_mainproject1.0.0
DISTDIR = /Users/halleking/cis330_mainproject/.tmp/cis330_mainproject1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/halleking/anaconda/lib
LIBS          = $(SUBLIBS) -L/Users/halleking/anaconda/lib -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5Network -lQt5Core -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_buttons.cpp \
		qrc_images.cpp \
		qrc_sounds.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_buttons.o \
		qrc_images.o \
		qrc_sounds.o \
		moc_mainwindow.o
DIST          = ../anaconda/mkspecs/features/spec_pre.prf \
		../anaconda/mkspecs/qdevice.pri \
		../anaconda/mkspecs/features/device_config.prf \
		../anaconda/mkspecs/common/unix.conf \
		../anaconda/mkspecs/common/mac.conf \
		../anaconda/mkspecs/common/macx.conf \
		../anaconda/mkspecs/common/sanitize.conf \
		../anaconda/mkspecs/common/gcc-base.conf \
		../anaconda/mkspecs/common/gcc-base-mac.conf \
		../anaconda/mkspecs/common/clang.conf \
		../anaconda/mkspecs/common/clang-mac.conf \
		../anaconda/mkspecs/qconfig.pri \
		../anaconda/mkspecs/modules/qt_lib_bluetooth.pri \
		../anaconda/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../anaconda/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../anaconda/mkspecs/modules/qt_lib_clucene_private.pri \
		../anaconda/mkspecs/modules/qt_lib_concurrent.pri \
		../anaconda/mkspecs/modules/qt_lib_concurrent_private.pri \
		../anaconda/mkspecs/modules/qt_lib_core.pri \
		../anaconda/mkspecs/modules/qt_lib_core_private.pri \
		../anaconda/mkspecs/modules/qt_lib_designer.pri \
		../anaconda/mkspecs/modules/qt_lib_designer_private.pri \
		../anaconda/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../anaconda/mkspecs/modules/qt_lib_gui.pri \
		../anaconda/mkspecs/modules/qt_lib_gui_private.pri \
		../anaconda/mkspecs/modules/qt_lib_help.pri \
		../anaconda/mkspecs/modules/qt_lib_help_private.pri \
		../anaconda/mkspecs/modules/qt_lib_macextras.pri \
		../anaconda/mkspecs/modules/qt_lib_macextras_private.pri \
		../anaconda/mkspecs/modules/qt_lib_multimedia.pri \
		../anaconda/mkspecs/modules/qt_lib_multimedia_private.pri \
		../anaconda/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../anaconda/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../anaconda/mkspecs/modules/qt_lib_network.pri \
		../anaconda/mkspecs/modules/qt_lib_network_private.pri \
		../anaconda/mkspecs/modules/qt_lib_nfc.pri \
		../anaconda/mkspecs/modules/qt_lib_nfc_private.pri \
		../anaconda/mkspecs/modules/qt_lib_opengl.pri \
		../anaconda/mkspecs/modules/qt_lib_opengl_private.pri \
		../anaconda/mkspecs/modules/qt_lib_openglextensions.pri \
		../anaconda/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../anaconda/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../anaconda/mkspecs/modules/qt_lib_printsupport.pri \
		../anaconda/mkspecs/modules/qt_lib_printsupport_private.pri \
		../anaconda/mkspecs/modules/qt_lib_qml.pri \
		../anaconda/mkspecs/modules/qt_lib_qml_private.pri \
		../anaconda/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../anaconda/mkspecs/modules/qt_lib_qmltest.pri \
		../anaconda/mkspecs/modules/qt_lib_qmltest_private.pri \
		../anaconda/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../anaconda/mkspecs/modules/qt_lib_quick.pri \
		../anaconda/mkspecs/modules/qt_lib_quick_private.pri \
		../anaconda/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../anaconda/mkspecs/modules/qt_lib_quickwidgets.pri \
		../anaconda/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../anaconda/mkspecs/modules/qt_lib_script.pri \
		../anaconda/mkspecs/modules/qt_lib_script_private.pri \
		../anaconda/mkspecs/modules/qt_lib_scripttools.pri \
		../anaconda/mkspecs/modules/qt_lib_scripttools_private.pri \
		../anaconda/mkspecs/modules/qt_lib_sql.pri \
		../anaconda/mkspecs/modules/qt_lib_sql_private.pri \
		../anaconda/mkspecs/modules/qt_lib_svg.pri \
		../anaconda/mkspecs/modules/qt_lib_svg_private.pri \
		../anaconda/mkspecs/modules/qt_lib_testlib.pri \
		../anaconda/mkspecs/modules/qt_lib_testlib_private.pri \
		../anaconda/mkspecs/modules/qt_lib_uiplugin.pri \
		../anaconda/mkspecs/modules/qt_lib_uitools.pri \
		../anaconda/mkspecs/modules/qt_lib_uitools_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webchannel.pri \
		../anaconda/mkspecs/modules/qt_lib_webchannel_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webengine.pri \
		../anaconda/mkspecs/modules/qt_lib_webengine_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webenginecore.pri \
		../anaconda/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../anaconda/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../anaconda/mkspecs/modules/qt_lib_websockets.pri \
		../anaconda/mkspecs/modules/qt_lib_websockets_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webview.pri \
		../anaconda/mkspecs/modules/qt_lib_webview_private.pri \
		../anaconda/mkspecs/modules/qt_lib_widgets.pri \
		../anaconda/mkspecs/modules/qt_lib_widgets_private.pri \
		../anaconda/mkspecs/modules/qt_lib_xml.pri \
		../anaconda/mkspecs/modules/qt_lib_xml_private.pri \
		../anaconda/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../anaconda/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../anaconda/mkspecs/features/qt_functions.prf \
		../anaconda/mkspecs/features/qt_config.prf \
		../anaconda/mkspecs/macx-clang/qmake.conf \
		../anaconda/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../anaconda/mkspecs/features/exclusive_builds.prf \
		../anaconda/mkspecs/features/default_pre.prf \
		../anaconda/mkspecs/features/mac/default_pre.prf \
		../anaconda/mkspecs/features/resolve_config.prf \
		../anaconda/mkspecs/features/default_post.prf \
		../anaconda/mkspecs/features/mac/sdk.prf \
		../anaconda/mkspecs/features/mac/default_post.prf \
		../anaconda/mkspecs/features/mac/objective_c.prf \
		../anaconda/mkspecs/features/warn_on.prf \
		../anaconda/mkspecs/features/qt.prf \
		../anaconda/mkspecs/features/resources.prf \
		../anaconda/mkspecs/features/moc.prf \
		../anaconda/mkspecs/features/unix/opengl.prf \
		../anaconda/mkspecs/features/uic.prf \
		../anaconda/mkspecs/features/unix/thread.prf \
		../anaconda/mkspecs/features/mac/rez.prf \
		../anaconda/mkspecs/features/testcase_targets.prf \
		../anaconda/mkspecs/features/exceptions.prf \
		../anaconda/mkspecs/features/yacc.prf \
		../anaconda/mkspecs/features/lex.prf \
		cis330_mainproject.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = cis330_mainproject
DESTDIR       = 
TARGET        = cis330_mainproject.app/Contents/MacOS/cis330_mainproject


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d cis330_mainproject.app/Contents/MacOS/ || mkdir -p cis330_mainproject.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cis330_mainproject.pro ../anaconda/mkspecs/macx-clang/qmake.conf ../anaconda/mkspecs/features/spec_pre.prf \
		../anaconda/mkspecs/qdevice.pri \
		../anaconda/mkspecs/features/device_config.prf \
		../anaconda/mkspecs/common/unix.conf \
		../anaconda/mkspecs/common/mac.conf \
		../anaconda/mkspecs/common/macx.conf \
		../anaconda/mkspecs/common/sanitize.conf \
		../anaconda/mkspecs/common/gcc-base.conf \
		../anaconda/mkspecs/common/gcc-base-mac.conf \
		../anaconda/mkspecs/common/clang.conf \
		../anaconda/mkspecs/common/clang-mac.conf \
		../anaconda/mkspecs/qconfig.pri \
		../anaconda/mkspecs/modules/qt_lib_bluetooth.pri \
		../anaconda/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../anaconda/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../anaconda/mkspecs/modules/qt_lib_clucene_private.pri \
		../anaconda/mkspecs/modules/qt_lib_concurrent.pri \
		../anaconda/mkspecs/modules/qt_lib_concurrent_private.pri \
		../anaconda/mkspecs/modules/qt_lib_core.pri \
		../anaconda/mkspecs/modules/qt_lib_core_private.pri \
		../anaconda/mkspecs/modules/qt_lib_designer.pri \
		../anaconda/mkspecs/modules/qt_lib_designer_private.pri \
		../anaconda/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../anaconda/mkspecs/modules/qt_lib_gui.pri \
		../anaconda/mkspecs/modules/qt_lib_gui_private.pri \
		../anaconda/mkspecs/modules/qt_lib_help.pri \
		../anaconda/mkspecs/modules/qt_lib_help_private.pri \
		../anaconda/mkspecs/modules/qt_lib_macextras.pri \
		../anaconda/mkspecs/modules/qt_lib_macextras_private.pri \
		../anaconda/mkspecs/modules/qt_lib_multimedia.pri \
		../anaconda/mkspecs/modules/qt_lib_multimedia_private.pri \
		../anaconda/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../anaconda/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../anaconda/mkspecs/modules/qt_lib_network.pri \
		../anaconda/mkspecs/modules/qt_lib_network_private.pri \
		../anaconda/mkspecs/modules/qt_lib_nfc.pri \
		../anaconda/mkspecs/modules/qt_lib_nfc_private.pri \
		../anaconda/mkspecs/modules/qt_lib_opengl.pri \
		../anaconda/mkspecs/modules/qt_lib_opengl_private.pri \
		../anaconda/mkspecs/modules/qt_lib_openglextensions.pri \
		../anaconda/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../anaconda/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../anaconda/mkspecs/modules/qt_lib_printsupport.pri \
		../anaconda/mkspecs/modules/qt_lib_printsupport_private.pri \
		../anaconda/mkspecs/modules/qt_lib_qml.pri \
		../anaconda/mkspecs/modules/qt_lib_qml_private.pri \
		../anaconda/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../anaconda/mkspecs/modules/qt_lib_qmltest.pri \
		../anaconda/mkspecs/modules/qt_lib_qmltest_private.pri \
		../anaconda/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../anaconda/mkspecs/modules/qt_lib_quick.pri \
		../anaconda/mkspecs/modules/qt_lib_quick_private.pri \
		../anaconda/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../anaconda/mkspecs/modules/qt_lib_quickwidgets.pri \
		../anaconda/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../anaconda/mkspecs/modules/qt_lib_script.pri \
		../anaconda/mkspecs/modules/qt_lib_script_private.pri \
		../anaconda/mkspecs/modules/qt_lib_scripttools.pri \
		../anaconda/mkspecs/modules/qt_lib_scripttools_private.pri \
		../anaconda/mkspecs/modules/qt_lib_sql.pri \
		../anaconda/mkspecs/modules/qt_lib_sql_private.pri \
		../anaconda/mkspecs/modules/qt_lib_svg.pri \
		../anaconda/mkspecs/modules/qt_lib_svg_private.pri \
		../anaconda/mkspecs/modules/qt_lib_testlib.pri \
		../anaconda/mkspecs/modules/qt_lib_testlib_private.pri \
		../anaconda/mkspecs/modules/qt_lib_uiplugin.pri \
		../anaconda/mkspecs/modules/qt_lib_uitools.pri \
		../anaconda/mkspecs/modules/qt_lib_uitools_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webchannel.pri \
		../anaconda/mkspecs/modules/qt_lib_webchannel_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webengine.pri \
		../anaconda/mkspecs/modules/qt_lib_webengine_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webenginecore.pri \
		../anaconda/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../anaconda/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../anaconda/mkspecs/modules/qt_lib_websockets.pri \
		../anaconda/mkspecs/modules/qt_lib_websockets_private.pri \
		../anaconda/mkspecs/modules/qt_lib_webview.pri \
		../anaconda/mkspecs/modules/qt_lib_webview_private.pri \
		../anaconda/mkspecs/modules/qt_lib_widgets.pri \
		../anaconda/mkspecs/modules/qt_lib_widgets_private.pri \
		../anaconda/mkspecs/modules/qt_lib_xml.pri \
		../anaconda/mkspecs/modules/qt_lib_xml_private.pri \
		../anaconda/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../anaconda/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../anaconda/mkspecs/features/qt_functions.prf \
		../anaconda/mkspecs/features/qt_config.prf \
		../anaconda/mkspecs/macx-clang/qmake.conf \
		../anaconda/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../anaconda/mkspecs/features/exclusive_builds.prf \
		../anaconda/mkspecs/features/default_pre.prf \
		../anaconda/mkspecs/features/mac/default_pre.prf \
		../anaconda/mkspecs/features/resolve_config.prf \
		../anaconda/mkspecs/features/default_post.prf \
		../anaconda/mkspecs/features/mac/sdk.prf \
		../anaconda/mkspecs/features/mac/default_post.prf \
		../anaconda/mkspecs/features/mac/objective_c.prf \
		../anaconda/mkspecs/features/warn_on.prf \
		../anaconda/mkspecs/features/qt.prf \
		../anaconda/mkspecs/features/resources.prf \
		../anaconda/mkspecs/features/moc.prf \
		../anaconda/mkspecs/features/unix/opengl.prf \
		../anaconda/mkspecs/features/uic.prf \
		../anaconda/mkspecs/features/unix/thread.prf \
		../anaconda/mkspecs/features/mac/rez.prf \
		../anaconda/mkspecs/features/testcase_targets.prf \
		../anaconda/mkspecs/features/exceptions.prf \
		../anaconda/mkspecs/features/yacc.prf \
		../anaconda/mkspecs/features/lex.prf \
		cis330_mainproject.pro \
		buttons.qrc \
		images.qrc \
		sounds.qrc \
		../anaconda/lib/libQt5Widgets.prl \
		../anaconda/lib/libQt5Multimedia.prl \
		../anaconda/lib/libQt5Gui.prl \
		../anaconda/lib/libQt5Network.prl \
		../anaconda/lib/libQt5Core.prl
	$(QMAKE) -o Makefile cis330_mainproject.pro
../anaconda/mkspecs/features/spec_pre.prf:
../anaconda/mkspecs/qdevice.pri:
../anaconda/mkspecs/features/device_config.prf:
../anaconda/mkspecs/common/unix.conf:
../anaconda/mkspecs/common/mac.conf:
../anaconda/mkspecs/common/macx.conf:
../anaconda/mkspecs/common/sanitize.conf:
../anaconda/mkspecs/common/gcc-base.conf:
../anaconda/mkspecs/common/gcc-base-mac.conf:
../anaconda/mkspecs/common/clang.conf:
../anaconda/mkspecs/common/clang-mac.conf:
../anaconda/mkspecs/qconfig.pri:
../anaconda/mkspecs/modules/qt_lib_bluetooth.pri:
../anaconda/mkspecs/modules/qt_lib_bluetooth_private.pri:
../anaconda/mkspecs/modules/qt_lib_bootstrap_private.pri:
../anaconda/mkspecs/modules/qt_lib_clucene_private.pri:
../anaconda/mkspecs/modules/qt_lib_concurrent.pri:
../anaconda/mkspecs/modules/qt_lib_concurrent_private.pri:
../anaconda/mkspecs/modules/qt_lib_core.pri:
../anaconda/mkspecs/modules/qt_lib_core_private.pri:
../anaconda/mkspecs/modules/qt_lib_designer.pri:
../anaconda/mkspecs/modules/qt_lib_designer_private.pri:
../anaconda/mkspecs/modules/qt_lib_designercomponents_private.pri:
../anaconda/mkspecs/modules/qt_lib_gui.pri:
../anaconda/mkspecs/modules/qt_lib_gui_private.pri:
../anaconda/mkspecs/modules/qt_lib_help.pri:
../anaconda/mkspecs/modules/qt_lib_help_private.pri:
../anaconda/mkspecs/modules/qt_lib_macextras.pri:
../anaconda/mkspecs/modules/qt_lib_macextras_private.pri:
../anaconda/mkspecs/modules/qt_lib_multimedia.pri:
../anaconda/mkspecs/modules/qt_lib_multimedia_private.pri:
../anaconda/mkspecs/modules/qt_lib_multimediawidgets.pri:
../anaconda/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../anaconda/mkspecs/modules/qt_lib_network.pri:
../anaconda/mkspecs/modules/qt_lib_network_private.pri:
../anaconda/mkspecs/modules/qt_lib_nfc.pri:
../anaconda/mkspecs/modules/qt_lib_nfc_private.pri:
../anaconda/mkspecs/modules/qt_lib_opengl.pri:
../anaconda/mkspecs/modules/qt_lib_opengl_private.pri:
../anaconda/mkspecs/modules/qt_lib_openglextensions.pri:
../anaconda/mkspecs/modules/qt_lib_openglextensions_private.pri:
../anaconda/mkspecs/modules/qt_lib_platformsupport_private.pri:
../anaconda/mkspecs/modules/qt_lib_printsupport.pri:
../anaconda/mkspecs/modules/qt_lib_printsupport_private.pri:
../anaconda/mkspecs/modules/qt_lib_qml.pri:
../anaconda/mkspecs/modules/qt_lib_qml_private.pri:
../anaconda/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../anaconda/mkspecs/modules/qt_lib_qmltest.pri:
../anaconda/mkspecs/modules/qt_lib_qmltest_private.pri:
../anaconda/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../anaconda/mkspecs/modules/qt_lib_quick.pri:
../anaconda/mkspecs/modules/qt_lib_quick_private.pri:
../anaconda/mkspecs/modules/qt_lib_quickparticles_private.pri:
../anaconda/mkspecs/modules/qt_lib_quickwidgets.pri:
../anaconda/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../anaconda/mkspecs/modules/qt_lib_script.pri:
../anaconda/mkspecs/modules/qt_lib_script_private.pri:
../anaconda/mkspecs/modules/qt_lib_scripttools.pri:
../anaconda/mkspecs/modules/qt_lib_scripttools_private.pri:
../anaconda/mkspecs/modules/qt_lib_sql.pri:
../anaconda/mkspecs/modules/qt_lib_sql_private.pri:
../anaconda/mkspecs/modules/qt_lib_svg.pri:
../anaconda/mkspecs/modules/qt_lib_svg_private.pri:
../anaconda/mkspecs/modules/qt_lib_testlib.pri:
../anaconda/mkspecs/modules/qt_lib_testlib_private.pri:
../anaconda/mkspecs/modules/qt_lib_uiplugin.pri:
../anaconda/mkspecs/modules/qt_lib_uitools.pri:
../anaconda/mkspecs/modules/qt_lib_uitools_private.pri:
../anaconda/mkspecs/modules/qt_lib_webchannel.pri:
../anaconda/mkspecs/modules/qt_lib_webchannel_private.pri:
../anaconda/mkspecs/modules/qt_lib_webengine.pri:
../anaconda/mkspecs/modules/qt_lib_webengine_private.pri:
../anaconda/mkspecs/modules/qt_lib_webenginecore.pri:
../anaconda/mkspecs/modules/qt_lib_webenginecore_private.pri:
../anaconda/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../anaconda/mkspecs/modules/qt_lib_webenginewidgets.pri:
../anaconda/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../anaconda/mkspecs/modules/qt_lib_websockets.pri:
../anaconda/mkspecs/modules/qt_lib_websockets_private.pri:
../anaconda/mkspecs/modules/qt_lib_webview.pri:
../anaconda/mkspecs/modules/qt_lib_webview_private.pri:
../anaconda/mkspecs/modules/qt_lib_widgets.pri:
../anaconda/mkspecs/modules/qt_lib_widgets_private.pri:
../anaconda/mkspecs/modules/qt_lib_xml.pri:
../anaconda/mkspecs/modules/qt_lib_xml_private.pri:
../anaconda/mkspecs/modules/qt_lib_xmlpatterns.pri:
../anaconda/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../anaconda/mkspecs/features/qt_functions.prf:
../anaconda/mkspecs/features/qt_config.prf:
../anaconda/mkspecs/macx-clang/qmake.conf:
../anaconda/mkspecs/features/spec_post.prf:
.qmake.stash:
../anaconda/mkspecs/features/exclusive_builds.prf:
../anaconda/mkspecs/features/default_pre.prf:
../anaconda/mkspecs/features/mac/default_pre.prf:
../anaconda/mkspecs/features/resolve_config.prf:
../anaconda/mkspecs/features/default_post.prf:
../anaconda/mkspecs/features/mac/sdk.prf:
../anaconda/mkspecs/features/mac/default_post.prf:
../anaconda/mkspecs/features/mac/objective_c.prf:
../anaconda/mkspecs/features/warn_on.prf:
../anaconda/mkspecs/features/qt.prf:
../anaconda/mkspecs/features/resources.prf:
../anaconda/mkspecs/features/moc.prf:
../anaconda/mkspecs/features/unix/opengl.prf:
../anaconda/mkspecs/features/uic.prf:
../anaconda/mkspecs/features/unix/thread.prf:
../anaconda/mkspecs/features/mac/rez.prf:
../anaconda/mkspecs/features/testcase_targets.prf:
../anaconda/mkspecs/features/exceptions.prf:
../anaconda/mkspecs/features/yacc.prf:
../anaconda/mkspecs/features/lex.prf:
cis330_mainproject.pro:
buttons.qrc:
images.qrc:
sounds.qrc:
../anaconda/lib/libQt5Widgets.prl:
../anaconda/lib/libQt5Multimedia.prl:
../anaconda/lib/libQt5Gui.prl:
../anaconda/lib/libQt5Network.prl:
../anaconda/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile cis330_mainproject.pro

qmake_all: FORCE

cis330_mainproject.app/Contents/PkgInfo: 
	@test -d cis330_mainproject.app/Contents || mkdir -p cis330_mainproject.app/Contents
	@$(DEL_FILE) cis330_mainproject.app/Contents/PkgInfo
	@echo "APPL????" > cis330_mainproject.app/Contents/PkgInfo
cis330_mainproject.app/Contents/Resources/empty.lproj: 
	@test -d cis330_mainproject.app/Contents/Resources || mkdir -p cis330_mainproject.app/Contents/Resources
	@touch cis330_mainproject.app/Contents/Resources/empty.lproj
	
cis330_mainproject.app/Contents/Info.plist: 
	@test -d cis330_mainproject.app/Contents || mkdir -p cis330_mainproject.app/Contents
	@$(DEL_FILE) cis330_mainproject.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,CIS314.cis330-mainproject,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,cis330_mainproject,g" -e "s,@LIBRARY@,cis330_mainproject,g" -e "s,@TYPEINFO@,????,g" ../anaconda/mkspecs/macx-clang/Info.plist.app >cis330_mainproject.app/Contents/Info.plist

all: Makefile \
		cis330_mainproject.app/Contents/PkgInfo \
		cis330_mainproject.app/Contents/Resources/empty.lproj \
		cis330_mainproject.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents buttons.qrc images.qrc sounds.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r cis330_mainproject.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_buttons.cpp qrc_images.cpp qrc_sounds.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_buttons.cpp qrc_images.cpp qrc_sounds.cpp
qrc_buttons.cpp: buttons.qrc \
		mainwindow.h \
		mainwindow.cpp \
		main.cpp \
		Buttons/orange_button.png \
		Buttons/blue_button.png \
		Buttons/green_button.png \
		Buttons/red_button.png \
		Buttons/StartButton.png \
		Buttons/yellow_button.png \
		Buttons/purple_button.png \
		Buttons/sendbutton.png \
		Buttons/Icons/4stars.png \
		Buttons/Icons/5stars.png \
		Buttons/Icons/star.png \
		Buttons/Icons/2stars.png \
		Buttons/Icons/3stars.png \
		../anaconda/include/qt/QtWidgets/QMainWindow \
		../anaconda/include/qt/QtWidgets/qmainwindow.h \
		../anaconda/include/qt/QtWidgets/qwidget.h \
		../anaconda/include/qt/QtGui/qwindowdefs.h \
		../anaconda/include/qt/QtCore/qglobal.h \
		../anaconda/include/qt/QtCore/qconfig.h \
		../anaconda/include/qt/QtCore/qfeatures.h \
		../anaconda/include/qt/QtCore/qsystemdetection.h \
		../anaconda/include/qt/QtCore/qprocessordetection.h \
		../anaconda/include/qt/QtCore/qcompilerdetection.h \
		../anaconda/include/qt/QtCore/qtypeinfo.h \
		../anaconda/include/qt/QtCore/qtypetraits.h \
		../anaconda/include/qt/QtCore/qisenum.h \
		../anaconda/include/qt/QtCore/qsysinfo.h \
		../anaconda/include/qt/QtCore/qlogging.h \
		../anaconda/include/qt/QtCore/qflags.h \
		../anaconda/include/qt/QtCore/qatomic.h \
		../anaconda/include/qt/QtCore/qbasicatomic.h \
		../anaconda/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda/include/qt/QtCore/qgenericatomic.h \
		../anaconda/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda/include/qt/QtCore/qatomic_gcc.h \
		../anaconda/include/qt/QtCore/qatomic_msvc.h \
		../anaconda/include/qt/QtCore/qatomic_armv7.h \
		../anaconda/include/qt/QtCore/qatomic_armv6.h \
		../anaconda/include/qt/QtCore/qatomic_armv5.h \
		../anaconda/include/qt/QtCore/qatomic_ia64.h \
		../anaconda/include/qt/QtCore/qatomic_x86.h \
		../anaconda/include/qt/QtCore/qatomic_unix.h \
		../anaconda/include/qt/QtCore/qglobalstatic.h \
		../anaconda/include/qt/QtCore/qmutex.h \
		../anaconda/include/qt/QtCore/qnumeric.h \
		../anaconda/include/qt/QtCore/qversiontagging.h \
		../anaconda/include/qt/QtCore/qobjectdefs.h \
		../anaconda/include/qt/QtCore/qnamespace.h \
		../anaconda/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda/include/qt/QtCore/qobject.h \
		../anaconda/include/qt/QtCore/qstring.h \
		../anaconda/include/qt/QtCore/qchar.h \
		../anaconda/include/qt/QtCore/qbytearray.h \
		../anaconda/include/qt/QtCore/qrefcount.h \
		../anaconda/include/qt/QtCore/qarraydata.h \
		../anaconda/include/qt/QtCore/qstringbuilder.h \
		../anaconda/include/qt/QtCore/qlist.h \
		../anaconda/include/qt/QtCore/qalgorithms.h \
		../anaconda/include/qt/QtCore/qiterator.h \
		../anaconda/include/qt/QtCore/qhashfunctions.h \
		../anaconda/include/qt/QtCore/qpair.h \
		../anaconda/include/qt/QtCore/qbytearraylist.h \
		../anaconda/include/qt/QtCore/qstringlist.h \
		../anaconda/include/qt/QtCore/qregexp.h \
		../anaconda/include/qt/QtCore/qstringmatcher.h \
		../anaconda/include/qt/QtCore/qcoreevent.h \
		../anaconda/include/qt/QtCore/qscopedpointer.h \
		../anaconda/include/qt/QtCore/qmetatype.h \
		../anaconda/include/qt/QtCore/qvarlengtharray.h \
		../anaconda/include/qt/QtCore/qcontainerfwd.h \
		../anaconda/include/qt/QtCore/qobject_impl.h \
		../anaconda/include/qt/QtCore/qmargins.h \
		../anaconda/include/qt/QtGui/qpaintdevice.h \
		../anaconda/include/qt/QtCore/qrect.h \
		../anaconda/include/qt/QtCore/qsize.h \
		../anaconda/include/qt/QtCore/qpoint.h \
		../anaconda/include/qt/QtGui/qpalette.h \
		../anaconda/include/qt/QtGui/qcolor.h \
		../anaconda/include/qt/QtGui/qrgb.h \
		../anaconda/include/qt/QtGui/qrgba64.h \
		../anaconda/include/qt/QtGui/qbrush.h \
		../anaconda/include/qt/QtCore/qvector.h \
		../anaconda/include/qt/QtGui/qmatrix.h \
		../anaconda/include/qt/QtGui/qpolygon.h \
		../anaconda/include/qt/QtGui/qregion.h \
		../anaconda/include/qt/QtCore/qdatastream.h \
		../anaconda/include/qt/QtCore/qiodevice.h \
		../anaconda/include/qt/QtCore/qline.h \
		../anaconda/include/qt/QtGui/qtransform.h \
		../anaconda/include/qt/QtGui/qpainterpath.h \
		../anaconda/include/qt/QtGui/qimage.h \
		../anaconda/include/qt/QtGui/qpixelformat.h \
		../anaconda/include/qt/QtGui/qpixmap.h \
		../anaconda/include/qt/QtCore/qsharedpointer.h \
		../anaconda/include/qt/QtCore/qshareddata.h \
		../anaconda/include/qt/QtCore/qhash.h \
		../anaconda/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda/include/qt/QtGui/qfont.h \
		../anaconda/include/qt/QtGui/qfontmetrics.h \
		../anaconda/include/qt/QtGui/qfontinfo.h \
		../anaconda/include/qt/QtWidgets/qsizepolicy.h \
		../anaconda/include/qt/QtGui/qcursor.h \
		../anaconda/include/qt/QtGui/qkeysequence.h \
		../anaconda/include/qt/QtGui/qevent.h \
		../anaconda/include/qt/QtCore/qvariant.h \
		../anaconda/include/qt/QtCore/qmap.h \
		../anaconda/include/qt/QtCore/qdebug.h \
		../anaconda/include/qt/QtCore/qtextstream.h \
		../anaconda/include/qt/QtCore/qlocale.h \
		../anaconda/include/qt/QtCore/qset.h \
		../anaconda/include/qt/QtCore/qcontiguouscache.h \
		../anaconda/include/qt/QtCore/qurl.h \
		../anaconda/include/qt/QtCore/qurlquery.h \
		../anaconda/include/qt/QtCore/qfile.h \
		../anaconda/include/qt/QtCore/qfiledevice.h \
		../anaconda/include/qt/QtGui/qvector2d.h \
		../anaconda/include/qt/QtGui/qtouchdevice.h \
		../anaconda/include/qt/QtWidgets/qtabwidget.h \
		../anaconda/include/qt/QtGui/qicon.h \
		../anaconda/include/qt/QtMultimedia/QMediaPlayer \
		../anaconda/include/qt/QtMultimedia/qmediaplayer.h \
		../anaconda/include/qt/QtMultimedia/qmediaobject.h \
		../anaconda/include/qt/QtMultimedia/qtmultimediadefs.h \
		../anaconda/include/qt/QtMultimedia/qmultimedia.h \
		../anaconda/include/qt/QtMultimedia/qmediacontent.h \
		../anaconda/include/qt/QtMultimedia/qmediaresource.h \
		../anaconda/include/qt/QtNetwork/qnetworkrequest.h \
		../anaconda/include/qt/QtCore/QSharedDataPointer \
		../anaconda/include/qt/QtCore/QString \
		../anaconda/include/qt/QtCore/QUrl \
		../anaconda/include/qt/QtCore/QVariant \
		../anaconda/include/qt/QtMultimedia/qmediaenumdebug.h \
		../anaconda/include/qt/QtCore/qmetaobject.h \
		../anaconda/include/qt/QtMultimedia/qaudio.h \
		../anaconda/include/qt/QtNetwork/qnetworkconfiguration.h \
		../anaconda/include/qt/QtWidgets/QProgressBar \
		../anaconda/include/qt/QtWidgets/qprogressbar.h \
		../anaconda/include/qt/QtWidgets/qframe.h \
		mainwindow.h \
		../anaconda/include/qt/QtWidgets/QMainWindow \
		../anaconda/include/qt/QtWidgets/qmainwindow.h \
		../anaconda/include/qt/QtWidgets/qwidget.h \
		../anaconda/include/qt/QtGui/qwindowdefs.h \
		../anaconda/include/qt/QtCore/qglobal.h \
		../anaconda/include/qt/QtCore/qconfig.h \
		../anaconda/include/qt/QtCore/qfeatures.h \
		../anaconda/include/qt/QtCore/qsystemdetection.h \
		../anaconda/include/qt/QtCore/qprocessordetection.h \
		../anaconda/include/qt/QtCore/qcompilerdetection.h \
		../anaconda/include/qt/QtCore/qtypeinfo.h \
		../anaconda/include/qt/QtCore/qtypetraits.h \
		../anaconda/include/qt/QtCore/qisenum.h \
		../anaconda/include/qt/QtCore/qsysinfo.h \
		../anaconda/include/qt/QtCore/qlogging.h \
		../anaconda/include/qt/QtCore/qflags.h \
		../anaconda/include/qt/QtCore/qatomic.h \
		../anaconda/include/qt/QtCore/qbasicatomic.h \
		../anaconda/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda/include/qt/QtCore/qgenericatomic.h \
		../anaconda/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda/include/qt/QtCore/qatomic_gcc.h \
		../anaconda/include/qt/QtCore/qatomic_msvc.h \
		../anaconda/include/qt/QtCore/qatomic_armv7.h \
		../anaconda/include/qt/QtCore/qatomic_armv6.h \
		../anaconda/include/qt/QtCore/qatomic_armv5.h \
		../anaconda/include/qt/QtCore/qatomic_ia64.h \
		../anaconda/include/qt/QtCore/qatomic_x86.h \
		../anaconda/include/qt/QtCore/qatomic_unix.h \
		../anaconda/include/qt/QtCore/qglobalstatic.h \
		../anaconda/include/qt/QtCore/qmutex.h \
		../anaconda/include/qt/QtCore/qnumeric.h \
		../anaconda/include/qt/QtCore/qversiontagging.h \
		../anaconda/include/qt/QtCore/qobjectdefs.h \
		../anaconda/include/qt/QtCore/qnamespace.h \
		../anaconda/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda/include/qt/QtCore/qobject.h \
		../anaconda/include/qt/QtCore/qstring.h \
		../anaconda/include/qt/QtCore/qchar.h \
		../anaconda/include/qt/QtCore/qbytearray.h \
		../anaconda/include/qt/QtCore/qrefcount.h \
		../anaconda/include/qt/QtCore/qarraydata.h \
		../anaconda/include/qt/QtCore/qstringbuilder.h \
		../anaconda/include/qt/QtCore/qlist.h \
		../anaconda/include/qt/QtCore/qalgorithms.h \
		../anaconda/include/qt/QtCore/qiterator.h \
		../anaconda/include/qt/QtCore/qhashfunctions.h \
		../anaconda/include/qt/QtCore/qpair.h \
		../anaconda/include/qt/QtCore/qbytearraylist.h \
		../anaconda/include/qt/QtCore/qstringlist.h \
		../anaconda/include/qt/QtCore/qregexp.h \
		../anaconda/include/qt/QtCore/qstringmatcher.h \
		../anaconda/include/qt/QtCore/qcoreevent.h \
		../anaconda/include/qt/QtCore/qscopedpointer.h \
		../anaconda/include/qt/QtCore/qmetatype.h \
		../anaconda/include/qt/QtCore/qvarlengtharray.h \
		../anaconda/include/qt/QtCore/qcontainerfwd.h \
		../anaconda/include/qt/QtCore/qobject_impl.h \
		../anaconda/include/qt/QtCore/qmargins.h \
		../anaconda/include/qt/QtGui/qpaintdevice.h \
		../anaconda/include/qt/QtCore/qrect.h \
		../anaconda/include/qt/QtCore/qsize.h \
		../anaconda/include/qt/QtCore/qpoint.h \
		../anaconda/include/qt/QtGui/qpalette.h \
		../anaconda/include/qt/QtGui/qcolor.h \
		../anaconda/include/qt/QtGui/qrgb.h \
		../anaconda/include/qt/QtGui/qrgba64.h \
		../anaconda/include/qt/QtGui/qbrush.h \
		../anaconda/include/qt/QtCore/qvector.h \
		../anaconda/include/qt/QtGui/qmatrix.h \
		../anaconda/include/qt/QtGui/qpolygon.h \
		../anaconda/include/qt/QtGui/qregion.h \
		../anaconda/include/qt/QtCore/qdatastream.h \
		../anaconda/include/qt/QtCore/qiodevice.h \
		../anaconda/include/qt/QtCore/qline.h \
		../anaconda/include/qt/QtGui/qtransform.h \
		../anaconda/include/qt/QtGui/qpainterpath.h \
		../anaconda/include/qt/QtGui/qimage.h \
		../anaconda/include/qt/QtGui/qpixelformat.h \
		../anaconda/include/qt/QtGui/qpixmap.h \
		../anaconda/include/qt/QtCore/qsharedpointer.h \
		../anaconda/include/qt/QtCore/qshareddata.h \
		../anaconda/include/qt/QtCore/qhash.h \
		../anaconda/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda/include/qt/QtGui/qfont.h \
		../anaconda/include/qt/QtGui/qfontmetrics.h \
		../anaconda/include/qt/QtGui/qfontinfo.h \
		../anaconda/include/qt/QtWidgets/qsizepolicy.h \
		../anaconda/include/qt/QtGui/qcursor.h \
		../anaconda/include/qt/QtGui/qkeysequence.h \
		../anaconda/include/qt/QtGui/qevent.h \
		../anaconda/include/qt/QtCore/qvariant.h \
		../anaconda/include/qt/QtCore/qmap.h \
		../anaconda/include/qt/QtCore/qdebug.h \
		../anaconda/include/qt/QtCore/qtextstream.h \
		../anaconda/include/qt/QtCore/qlocale.h \
		../anaconda/include/qt/QtCore/qset.h \
		../anaconda/include/qt/QtCore/qcontiguouscache.h \
		../anaconda/include/qt/QtCore/qurl.h \
		../anaconda/include/qt/QtCore/qurlquery.h \
		../anaconda/include/qt/QtCore/qfile.h \
		../anaconda/include/qt/QtCore/qfiledevice.h \
		../anaconda/include/qt/QtGui/qvector2d.h \
		../anaconda/include/qt/QtGui/qtouchdevice.h \
		../anaconda/include/qt/QtWidgets/qtabwidget.h \
		../anaconda/include/qt/QtGui/qicon.h \
		../anaconda/include/qt/QtMultimedia/QMediaPlayer \
		../anaconda/include/qt/QtMultimedia/qmediaplayer.h \
		../anaconda/include/qt/QtMultimedia/qmediaobject.h \
		../anaconda/include/qt/QtMultimedia/qtmultimediadefs.h \
		../anaconda/include/qt/QtMultimedia/qmultimedia.h \
		../anaconda/include/qt/QtMultimedia/qmediacontent.h \
		../anaconda/include/qt/QtMultimedia/qmediaresource.h \
		../anaconda/include/qt/QtNetwork/qnetworkrequest.h \
		../anaconda/include/qt/QtCore/QSharedDataPointer \
		../anaconda/include/qt/QtCore/QString \
		../anaconda/include/qt/QtCore/QUrl \
		../anaconda/include/qt/QtCore/QVariant \
		../anaconda/include/qt/QtMultimedia/qmediaenumdebug.h \
		../anaconda/include/qt/QtCore/qmetaobject.h \
		../anaconda/include/qt/QtMultimedia/qaudio.h \
		../anaconda/include/qt/QtNetwork/qnetworkconfiguration.h \
		../anaconda/include/qt/QtWidgets/QProgressBar \
		../anaconda/include/qt/QtWidgets/qprogressbar.h \
		../anaconda/include/qt/QtWidgets/qframe.h \
		ui_mainwindow.h \
		../anaconda/include/qt/QtWidgets/QAction \
		../anaconda/include/qt/QtWidgets/qaction.h \
		../anaconda/include/qt/QtWidgets/qactiongroup.h \
		../anaconda/include/qt/QtWidgets/QApplication \
		../anaconda/include/qt/QtWidgets/qapplication.h \
		../anaconda/include/qt/QtCore/qcoreapplication.h \
		../anaconda/include/qt/QtCore/qeventloop.h \
		../anaconda/include/qt/QtWidgets/qdesktopwidget.h \
		../anaconda/include/qt/QtGui/qguiapplication.h \
		../anaconda/include/qt/QtGui/qinputmethod.h \
		../anaconda/include/qt/QtWidgets/QButtonGroup \
		../anaconda/include/qt/QtWidgets/qbuttongroup.h \
		../anaconda/include/qt/QtWidgets/QHeaderView \
		../anaconda/include/qt/QtWidgets/qheaderview.h \
		../anaconda/include/qt/QtWidgets/qabstractitemview.h \
		../anaconda/include/qt/QtWidgets/qabstractscrollarea.h \
		../anaconda/include/qt/QtCore/qabstractitemmodel.h \
		../anaconda/include/qt/QtCore/qitemselectionmodel.h \
		../anaconda/include/qt/QtWidgets/qabstractitemdelegate.h \
		../anaconda/include/qt/QtWidgets/qstyleoption.h \
		../anaconda/include/qt/QtWidgets/qabstractspinbox.h \
		../anaconda/include/qt/QtGui/qvalidator.h \
		../anaconda/include/qt/QtCore/qregularexpression.h \
		../anaconda/include/qt/QtWidgets/qslider.h \
		../anaconda/include/qt/QtWidgets/qabstractslider.h \
		../anaconda/include/qt/QtWidgets/qstyle.h \
		../anaconda/include/qt/QtWidgets/qtabbar.h \
		../anaconda/include/qt/QtWidgets/qrubberband.h \
		../anaconda/include/qt/QtWidgets/QLabel \
		../anaconda/include/qt/QtWidgets/qlabel.h \
		../anaconda/include/qt/QtWidgets/QPushButton \
		../anaconda/include/qt/QtWidgets/qpushbutton.h \
		../anaconda/include/qt/QtWidgets/qabstractbutton.h \
		../anaconda/include/qt/QtWidgets/QStatusBar \
		../anaconda/include/qt/QtWidgets/qstatusbar.h \
		../anaconda/include/qt/QtWidgets/QTextEdit \
		../anaconda/include/qt/QtWidgets/qtextedit.h \
		../anaconda/include/qt/QtGui/qtextdocument.h \
		../anaconda/include/qt/QtGui/qtextoption.h \
		../anaconda/include/qt/QtGui/qtextcursor.h \
		../anaconda/include/qt/QtGui/qtextformat.h \
		../anaconda/include/qt/QtGui/qpen.h \
		../anaconda/include/qt/QtWidgets/QToolBar \
		../anaconda/include/qt/QtWidgets/qtoolbar.h \
		../anaconda/include/qt/QtWidgets/QWidget \
		../anaconda/include/qt/QtCore/QTime \
		../anaconda/include/qt/QtCore/qdatetime.h \
		../anaconda/include/qt/QtGui/QPixmap \
		mainwindow.h \
		../anaconda/include/qt/QtWidgets/QMainWindow \
		../anaconda/include/qt/QtWidgets/qmainwindow.h \
		../anaconda/include/qt/QtWidgets/qwidget.h \
		../anaconda/include/qt/QtGui/qwindowdefs.h \
		../anaconda/include/qt/QtCore/qglobal.h \
		../anaconda/include/qt/QtCore/qconfig.h \
		../anaconda/include/qt/QtCore/qfeatures.h \
		../anaconda/include/qt/QtCore/qsystemdetection.h \
		../anaconda/include/qt/QtCore/qprocessordetection.h \
		../anaconda/include/qt/QtCore/qcompilerdetection.h \
		../anaconda/include/qt/QtCore/qtypeinfo.h \
		../anaconda/include/qt/QtCore/qtypetraits.h \
		../anaconda/include/qt/QtCore/qisenum.h \
		../anaconda/include/qt/QtCore/qsysinfo.h \
		../anaconda/include/qt/QtCore/qlogging.h \
		../anaconda/include/qt/QtCore/qflags.h \
		../anaconda/include/qt/QtCore/qatomic.h \
		../anaconda/include/qt/QtCore/qbasicatomic.h \
		../anaconda/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda/include/qt/QtCore/qgenericatomic.h \
		../anaconda/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda/include/qt/QtCore/qatomic_gcc.h \
		../anaconda/include/qt/QtCore/qatomic_msvc.h \
		../anaconda/include/qt/QtCore/qatomic_armv7.h \
		../anaconda/include/qt/QtCore/qatomic_armv6.h \
		../anaconda/include/qt/QtCore/qatomic_armv5.h \
		../anaconda/include/qt/QtCore/qatomic_ia64.h \
		../anaconda/include/qt/QtCore/qatomic_x86.h \
		../anaconda/include/qt/QtCore/qatomic_unix.h \
		../anaconda/include/qt/QtCore/qglobalstatic.h \
		../anaconda/include/qt/QtCore/qmutex.h \
		../anaconda/include/qt/QtCore/qnumeric.h \
		../anaconda/include/qt/QtCore/qversiontagging.h \
		../anaconda/include/qt/QtCore/qobjectdefs.h \
		../anaconda/include/qt/QtCore/qnamespace.h \
		../anaconda/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda/include/qt/QtCore/qobject.h \
		../anaconda/include/qt/QtCore/qstring.h \
		../anaconda/include/qt/QtCore/qchar.h \
		../anaconda/include/qt/QtCore/qbytearray.h \
		../anaconda/include/qt/QtCore/qrefcount.h \
		../anaconda/include/qt/QtCore/qarraydata.h \
		../anaconda/include/qt/QtCore/qstringbuilder.h \
		../anaconda/include/qt/QtCore/qlist.h \
		../anaconda/include/qt/QtCore/qalgorithms.h \
		../anaconda/include/qt/QtCore/qiterator.h \
		../anaconda/include/qt/QtCore/qhashfunctions.h \
		../anaconda/include/qt/QtCore/qpair.h \
		../anaconda/include/qt/QtCore/qbytearraylist.h \
		../anaconda/include/qt/QtCore/qstringlist.h \
		../anaconda/include/qt/QtCore/qregexp.h \
		../anaconda/include/qt/QtCore/qstringmatcher.h \
		../anaconda/include/qt/QtCore/qcoreevent.h \
		../anaconda/include/qt/QtCore/qscopedpointer.h \
		../anaconda/include/qt/QtCore/qmetatype.h \
		../anaconda/include/qt/QtCore/qvarlengtharray.h \
		../anaconda/include/qt/QtCore/qcontainerfwd.h \
		../anaconda/include/qt/QtCore/qobject_impl.h \
		../anaconda/include/qt/QtCore/qmargins.h \
		../anaconda/include/qt/QtGui/qpaintdevice.h \
		../anaconda/include/qt/QtCore/qrect.h \
		../anaconda/include/qt/QtCore/qsize.h \
		../anaconda/include/qt/QtCore/qpoint.h \
		../anaconda/include/qt/QtGui/qpalette.h \
		../anaconda/include/qt/QtGui/qcolor.h \
		../anaconda/include/qt/QtGui/qrgb.h \
		../anaconda/include/qt/QtGui/qrgba64.h \
		../anaconda/include/qt/QtGui/qbrush.h \
		../anaconda/include/qt/QtCore/qvector.h \
		../anaconda/include/qt/QtGui/qmatrix.h \
		../anaconda/include/qt/QtGui/qpolygon.h \
		../anaconda/include/qt/QtGui/qregion.h \
		../anaconda/include/qt/QtCore/qdatastream.h \
		../anaconda/include/qt/QtCore/qiodevice.h \
		../anaconda/include/qt/QtCore/qline.h \
		../anaconda/include/qt/QtGui/qtransform.h \
		../anaconda/include/qt/QtGui/qpainterpath.h \
		../anaconda/include/qt/QtGui/qimage.h \
		../anaconda/include/qt/QtGui/qpixelformat.h \
		../anaconda/include/qt/QtGui/qpixmap.h \
		../anaconda/include/qt/QtCore/qsharedpointer.h \
		../anaconda/include/qt/QtCore/qshareddata.h \
		../anaconda/include/qt/QtCore/qhash.h \
		../anaconda/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda/include/qt/QtGui/qfont.h \
		../anaconda/include/qt/QtGui/qfontmetrics.h \
		../anaconda/include/qt/QtGui/qfontinfo.h \
		../anaconda/include/qt/QtWidgets/qsizepolicy.h \
		../anaconda/include/qt/QtGui/qcursor.h \
		../anaconda/include/qt/QtGui/qkeysequence.h \
		../anaconda/include/qt/QtGui/qevent.h \
		../anaconda/include/qt/QtCore/qvariant.h \
		../anaconda/include/qt/QtCore/qmap.h \
		../anaconda/include/qt/QtCore/qdebug.h \
		../anaconda/include/qt/QtCore/qtextstream.h \
		../anaconda/include/qt/QtCore/qlocale.h \
		../anaconda/include/qt/QtCore/qset.h \
		../anaconda/include/qt/QtCore/qcontiguouscache.h \
		../anaconda/include/qt/QtCore/qurl.h \
		../anaconda/include/qt/QtCore/qurlquery.h \
		../anaconda/include/qt/QtCore/qfile.h \
		../anaconda/include/qt/QtCore/qfiledevice.h \
		../anaconda/include/qt/QtGui/qvector2d.h \
		../anaconda/include/qt/QtGui/qtouchdevice.h \
		../anaconda/include/qt/QtWidgets/qtabwidget.h \
		../anaconda/include/qt/QtGui/qicon.h \
		../anaconda/include/qt/QtMultimedia/QMediaPlayer \
		../anaconda/include/qt/QtMultimedia/qmediaplayer.h \
		../anaconda/include/qt/QtMultimedia/qmediaobject.h \
		../anaconda/include/qt/QtMultimedia/qtmultimediadefs.h \
		../anaconda/include/qt/QtMultimedia/qmultimedia.h \
		../anaconda/include/qt/QtMultimedia/qmediacontent.h \
		../anaconda/include/qt/QtMultimedia/qmediaresource.h \
		../anaconda/include/qt/QtNetwork/qnetworkrequest.h \
		../anaconda/include/qt/QtCore/QSharedDataPointer \
		../anaconda/include/qt/QtCore/QString \
		../anaconda/include/qt/QtCore/QUrl \
		../anaconda/include/qt/QtCore/QVariant \
		../anaconda/include/qt/QtMultimedia/qmediaenumdebug.h \
		../anaconda/include/qt/QtCore/qmetaobject.h \
		../anaconda/include/qt/QtMultimedia/qaudio.h \
		../anaconda/include/qt/QtNetwork/qnetworkconfiguration.h \
		../anaconda/include/qt/QtWidgets/QProgressBar \
		../anaconda/include/qt/QtWidgets/qprogressbar.h \
		../anaconda/include/qt/QtWidgets/qframe.h \
		../anaconda/include/qt/QtWidgets/QApplication \
		../anaconda/include/qt/QtWidgets/qapplication.h \
		../anaconda/include/qt/QtCore/qcoreapplication.h \
		../anaconda/include/qt/QtCore/qeventloop.h \
		../anaconda/include/qt/QtWidgets/qdesktopwidget.h \
		../anaconda/include/qt/QtGui/qguiapplication.h \
		../anaconda/include/qt/QtGui/qinputmethod.h
	/Users/halleking/anaconda/bin/rcc -name buttons buttons.qrc -o qrc_buttons.cpp

qrc_images.cpp: images.qrc \
		neon-cat-clipart-4.gif \
		sad-cat.png
	/Users/halleking/anaconda/bin/rcc -name images images.qrc -o qrc_images.cpp

qrc_sounds.cpp: sounds.qrc \
		fail-buzzer-04.mp3 \
		Button5.wav \
		Button4.wav \
		Button3.wav \
		Button2.wav \
		Button6.wav \
		Button1.wav
	/Users/halleking/anaconda/bin/rcc -name sounds sounds.qrc -o qrc_sounds.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../anaconda/include/qt/QtWidgets/QMainWindow \
		../anaconda/include/qt/QtWidgets/qmainwindow.h \
		../anaconda/include/qt/QtWidgets/qwidget.h \
		../anaconda/include/qt/QtGui/qwindowdefs.h \
		../anaconda/include/qt/QtCore/qglobal.h \
		../anaconda/include/qt/QtCore/qconfig.h \
		../anaconda/include/qt/QtCore/qfeatures.h \
		../anaconda/include/qt/QtCore/qsystemdetection.h \
		../anaconda/include/qt/QtCore/qprocessordetection.h \
		../anaconda/include/qt/QtCore/qcompilerdetection.h \
		../anaconda/include/qt/QtCore/qtypeinfo.h \
		../anaconda/include/qt/QtCore/qtypetraits.h \
		../anaconda/include/qt/QtCore/qisenum.h \
		../anaconda/include/qt/QtCore/qsysinfo.h \
		../anaconda/include/qt/QtCore/qlogging.h \
		../anaconda/include/qt/QtCore/qflags.h \
		../anaconda/include/qt/QtCore/qatomic.h \
		../anaconda/include/qt/QtCore/qbasicatomic.h \
		../anaconda/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda/include/qt/QtCore/qgenericatomic.h \
		../anaconda/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda/include/qt/QtCore/qatomic_gcc.h \
		../anaconda/include/qt/QtCore/qatomic_msvc.h \
		../anaconda/include/qt/QtCore/qatomic_armv7.h \
		../anaconda/include/qt/QtCore/qatomic_armv6.h \
		../anaconda/include/qt/QtCore/qatomic_armv5.h \
		../anaconda/include/qt/QtCore/qatomic_ia64.h \
		../anaconda/include/qt/QtCore/qatomic_x86.h \
		../anaconda/include/qt/QtCore/qatomic_unix.h \
		../anaconda/include/qt/QtCore/qglobalstatic.h \
		../anaconda/include/qt/QtCore/qmutex.h \
		../anaconda/include/qt/QtCore/qnumeric.h \
		../anaconda/include/qt/QtCore/qversiontagging.h \
		../anaconda/include/qt/QtCore/qobjectdefs.h \
		../anaconda/include/qt/QtCore/qnamespace.h \
		../anaconda/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda/include/qt/QtCore/qobject.h \
		../anaconda/include/qt/QtCore/qstring.h \
		../anaconda/include/qt/QtCore/qchar.h \
		../anaconda/include/qt/QtCore/qbytearray.h \
		../anaconda/include/qt/QtCore/qrefcount.h \
		../anaconda/include/qt/QtCore/qarraydata.h \
		../anaconda/include/qt/QtCore/qstringbuilder.h \
		../anaconda/include/qt/QtCore/qlist.h \
		../anaconda/include/qt/QtCore/qalgorithms.h \
		../anaconda/include/qt/QtCore/qiterator.h \
		../anaconda/include/qt/QtCore/qhashfunctions.h \
		../anaconda/include/qt/QtCore/qpair.h \
		../anaconda/include/qt/QtCore/qbytearraylist.h \
		../anaconda/include/qt/QtCore/qstringlist.h \
		../anaconda/include/qt/QtCore/qregexp.h \
		../anaconda/include/qt/QtCore/qstringmatcher.h \
		../anaconda/include/qt/QtCore/qcoreevent.h \
		../anaconda/include/qt/QtCore/qscopedpointer.h \
		../anaconda/include/qt/QtCore/qmetatype.h \
		../anaconda/include/qt/QtCore/qvarlengtharray.h \
		../anaconda/include/qt/QtCore/qcontainerfwd.h \
		../anaconda/include/qt/QtCore/qobject_impl.h \
		../anaconda/include/qt/QtCore/qmargins.h \
		../anaconda/include/qt/QtGui/qpaintdevice.h \
		../anaconda/include/qt/QtCore/qrect.h \
		../anaconda/include/qt/QtCore/qsize.h \
		../anaconda/include/qt/QtCore/qpoint.h \
		../anaconda/include/qt/QtGui/qpalette.h \
		../anaconda/include/qt/QtGui/qcolor.h \
		../anaconda/include/qt/QtGui/qrgb.h \
		../anaconda/include/qt/QtGui/qrgba64.h \
		../anaconda/include/qt/QtGui/qbrush.h \
		../anaconda/include/qt/QtCore/qvector.h \
		../anaconda/include/qt/QtGui/qmatrix.h \
		../anaconda/include/qt/QtGui/qpolygon.h \
		../anaconda/include/qt/QtGui/qregion.h \
		../anaconda/include/qt/QtCore/qdatastream.h \
		../anaconda/include/qt/QtCore/qiodevice.h \
		../anaconda/include/qt/QtCore/qline.h \
		../anaconda/include/qt/QtGui/qtransform.h \
		../anaconda/include/qt/QtGui/qpainterpath.h \
		../anaconda/include/qt/QtGui/qimage.h \
		../anaconda/include/qt/QtGui/qpixelformat.h \
		../anaconda/include/qt/QtGui/qpixmap.h \
		../anaconda/include/qt/QtCore/qsharedpointer.h \
		../anaconda/include/qt/QtCore/qshareddata.h \
		../anaconda/include/qt/QtCore/qhash.h \
		../anaconda/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda/include/qt/QtGui/qfont.h \
		../anaconda/include/qt/QtGui/qfontmetrics.h \
		../anaconda/include/qt/QtGui/qfontinfo.h \
		../anaconda/include/qt/QtWidgets/qsizepolicy.h \
		../anaconda/include/qt/QtGui/qcursor.h \
		../anaconda/include/qt/QtGui/qkeysequence.h \
		../anaconda/include/qt/QtGui/qevent.h \
		../anaconda/include/qt/QtCore/qvariant.h \
		../anaconda/include/qt/QtCore/qmap.h \
		../anaconda/include/qt/QtCore/qdebug.h \
		../anaconda/include/qt/QtCore/qtextstream.h \
		../anaconda/include/qt/QtCore/qlocale.h \
		../anaconda/include/qt/QtCore/qset.h \
		../anaconda/include/qt/QtCore/qcontiguouscache.h \
		../anaconda/include/qt/QtCore/qurl.h \
		../anaconda/include/qt/QtCore/qurlquery.h \
		../anaconda/include/qt/QtCore/qfile.h \
		../anaconda/include/qt/QtCore/qfiledevice.h \
		../anaconda/include/qt/QtGui/qvector2d.h \
		../anaconda/include/qt/QtGui/qtouchdevice.h \
		../anaconda/include/qt/QtWidgets/qtabwidget.h \
		../anaconda/include/qt/QtGui/qicon.h \
		../anaconda/include/qt/QtMultimedia/QMediaPlayer \
		../anaconda/include/qt/QtMultimedia/qmediaplayer.h \
		../anaconda/include/qt/QtMultimedia/qmediaobject.h \
		../anaconda/include/qt/QtMultimedia/qtmultimediadefs.h \
		../anaconda/include/qt/QtMultimedia/qmultimedia.h \
		../anaconda/include/qt/QtMultimedia/qmediacontent.h \
		../anaconda/include/qt/QtMultimedia/qmediaresource.h \
		../anaconda/include/qt/QtNetwork/qnetworkrequest.h \
		../anaconda/include/qt/QtCore/QSharedDataPointer \
		../anaconda/include/qt/QtCore/QString \
		../anaconda/include/qt/QtCore/QUrl \
		../anaconda/include/qt/QtCore/QVariant \
		../anaconda/include/qt/QtMultimedia/qmediaenumdebug.h \
		../anaconda/include/qt/QtCore/qmetaobject.h \
		../anaconda/include/qt/QtMultimedia/qaudio.h \
		../anaconda/include/qt/QtNetwork/qnetworkconfiguration.h \
		../anaconda/include/qt/QtWidgets/QProgressBar \
		../anaconda/include/qt/QtWidgets/qprogressbar.h \
		../anaconda/include/qt/QtWidgets/qframe.h \
		mainwindow.h
	/Users/halleking/anaconda/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/halleking/anaconda/mkspecs/macx-clang -I/Users/halleking/cis330_mainproject -I/Users/halleking/cis330_mainproject -I/Users/halleking/anaconda/include/qt -I/Users/halleking/anaconda/include/qt/QtWidgets -I/Users/halleking/anaconda/include/qt/QtMultimedia -I/Users/halleking/anaconda/include/qt/QtGui -I/Users/halleking/anaconda/include/qt/QtNetwork -I/Users/halleking/anaconda/include/qt/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/halleking/anaconda/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../anaconda/include/qt/QtWidgets/QMainWindow \
		../anaconda/include/qt/QtWidgets/qmainwindow.h \
		../anaconda/include/qt/QtWidgets/qwidget.h \
		../anaconda/include/qt/QtGui/qwindowdefs.h \
		../anaconda/include/qt/QtCore/qglobal.h \
		../anaconda/include/qt/QtCore/qconfig.h \
		../anaconda/include/qt/QtCore/qfeatures.h \
		../anaconda/include/qt/QtCore/qsystemdetection.h \
		../anaconda/include/qt/QtCore/qprocessordetection.h \
		../anaconda/include/qt/QtCore/qcompilerdetection.h \
		../anaconda/include/qt/QtCore/qtypeinfo.h \
		../anaconda/include/qt/QtCore/qtypetraits.h \
		../anaconda/include/qt/QtCore/qisenum.h \
		../anaconda/include/qt/QtCore/qsysinfo.h \
		../anaconda/include/qt/QtCore/qlogging.h \
		../anaconda/include/qt/QtCore/qflags.h \
		../anaconda/include/qt/QtCore/qatomic.h \
		../anaconda/include/qt/QtCore/qbasicatomic.h \
		../anaconda/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda/include/qt/QtCore/qgenericatomic.h \
		../anaconda/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda/include/qt/QtCore/qatomic_gcc.h \
		../anaconda/include/qt/QtCore/qatomic_msvc.h \
		../anaconda/include/qt/QtCore/qatomic_armv7.h \
		../anaconda/include/qt/QtCore/qatomic_armv6.h \
		../anaconda/include/qt/QtCore/qatomic_armv5.h \
		../anaconda/include/qt/QtCore/qatomic_ia64.h \
		../anaconda/include/qt/QtCore/qatomic_x86.h \
		../anaconda/include/qt/QtCore/qatomic_unix.h \
		../anaconda/include/qt/QtCore/qglobalstatic.h \
		../anaconda/include/qt/QtCore/qmutex.h \
		../anaconda/include/qt/QtCore/qnumeric.h \
		../anaconda/include/qt/QtCore/qversiontagging.h \
		../anaconda/include/qt/QtCore/qobjectdefs.h \
		../anaconda/include/qt/QtCore/qnamespace.h \
		../anaconda/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda/include/qt/QtCore/qobject.h \
		../anaconda/include/qt/QtCore/qstring.h \
		../anaconda/include/qt/QtCore/qchar.h \
		../anaconda/include/qt/QtCore/qbytearray.h \
		../anaconda/include/qt/QtCore/qrefcount.h \
		../anaconda/include/qt/QtCore/qarraydata.h \
		../anaconda/include/qt/QtCore/qstringbuilder.h \
		../anaconda/include/qt/QtCore/qlist.h \
		../anaconda/include/qt/QtCore/qalgorithms.h \
		../anaconda/include/qt/QtCore/qiterator.h \
		../anaconda/include/qt/QtCore/qhashfunctions.h \
		../anaconda/include/qt/QtCore/qpair.h \
		../anaconda/include/qt/QtCore/qbytearraylist.h \
		../anaconda/include/qt/QtCore/qstringlist.h \
		../anaconda/include/qt/QtCore/qregexp.h \
		../anaconda/include/qt/QtCore/qstringmatcher.h \
		../anaconda/include/qt/QtCore/qcoreevent.h \
		../anaconda/include/qt/QtCore/qscopedpointer.h \
		../anaconda/include/qt/QtCore/qmetatype.h \
		../anaconda/include/qt/QtCore/qvarlengtharray.h \
		../anaconda/include/qt/QtCore/qcontainerfwd.h \
		../anaconda/include/qt/QtCore/qobject_impl.h \
		../anaconda/include/qt/QtCore/qmargins.h \
		../anaconda/include/qt/QtGui/qpaintdevice.h \
		../anaconda/include/qt/QtCore/qrect.h \
		../anaconda/include/qt/QtCore/qsize.h \
		../anaconda/include/qt/QtCore/qpoint.h \
		../anaconda/include/qt/QtGui/qpalette.h \
		../anaconda/include/qt/QtGui/qcolor.h \
		../anaconda/include/qt/QtGui/qrgb.h \
		../anaconda/include/qt/QtGui/qrgba64.h \
		../anaconda/include/qt/QtGui/qbrush.h \
		../anaconda/include/qt/QtCore/qvector.h \
		../anaconda/include/qt/QtGui/qmatrix.h \
		../anaconda/include/qt/QtGui/qpolygon.h \
		../anaconda/include/qt/QtGui/qregion.h \
		../anaconda/include/qt/QtCore/qdatastream.h \
		../anaconda/include/qt/QtCore/qiodevice.h \
		../anaconda/include/qt/QtCore/qline.h \
		../anaconda/include/qt/QtGui/qtransform.h \
		../anaconda/include/qt/QtGui/qpainterpath.h \
		../anaconda/include/qt/QtGui/qimage.h \
		../anaconda/include/qt/QtGui/qpixelformat.h \
		../anaconda/include/qt/QtGui/qpixmap.h \
		../anaconda/include/qt/QtCore/qsharedpointer.h \
		../anaconda/include/qt/QtCore/qshareddata.h \
		../anaconda/include/qt/QtCore/qhash.h \
		../anaconda/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda/include/qt/QtGui/qfont.h \
		../anaconda/include/qt/QtGui/qfontmetrics.h \
		../anaconda/include/qt/QtGui/qfontinfo.h \
		../anaconda/include/qt/QtWidgets/qsizepolicy.h \
		../anaconda/include/qt/QtGui/qcursor.h \
		../anaconda/include/qt/QtGui/qkeysequence.h \
		../anaconda/include/qt/QtGui/qevent.h \
		../anaconda/include/qt/QtCore/qvariant.h \
		../anaconda/include/qt/QtCore/qmap.h \
		../anaconda/include/qt/QtCore/qdebug.h \
		../anaconda/include/qt/QtCore/qtextstream.h \
		../anaconda/include/qt/QtCore/qlocale.h \
		../anaconda/include/qt/QtCore/qset.h \
		../anaconda/include/qt/QtCore/qcontiguouscache.h \
		../anaconda/include/qt/QtCore/qurl.h \
		../anaconda/include/qt/QtCore/qurlquery.h \
		../anaconda/include/qt/QtCore/qfile.h \
		../anaconda/include/qt/QtCore/qfiledevice.h \
		../anaconda/include/qt/QtGui/qvector2d.h \
		../anaconda/include/qt/QtGui/qtouchdevice.h \
		../anaconda/include/qt/QtWidgets/qtabwidget.h \
		../anaconda/include/qt/QtGui/qicon.h \
		../anaconda/include/qt/QtMultimedia/QMediaPlayer \
		../anaconda/include/qt/QtMultimedia/qmediaplayer.h \
		../anaconda/include/qt/QtMultimedia/qmediaobject.h \
		../anaconda/include/qt/QtMultimedia/qtmultimediadefs.h \
		../anaconda/include/qt/QtMultimedia/qmultimedia.h \
		../anaconda/include/qt/QtMultimedia/qmediacontent.h \
		../anaconda/include/qt/QtMultimedia/qmediaresource.h \
		../anaconda/include/qt/QtNetwork/qnetworkrequest.h \
		../anaconda/include/qt/QtCore/QSharedDataPointer \
		../anaconda/include/qt/QtCore/QString \
		../anaconda/include/qt/QtCore/QUrl \
		../anaconda/include/qt/QtCore/QVariant \
		../anaconda/include/qt/QtMultimedia/qmediaenumdebug.h \
		../anaconda/include/qt/QtCore/qmetaobject.h \
		../anaconda/include/qt/QtMultimedia/qaudio.h \
		../anaconda/include/qt/QtNetwork/qnetworkconfiguration.h \
		../anaconda/include/qt/QtWidgets/QProgressBar \
		../anaconda/include/qt/QtWidgets/qprogressbar.h \
		../anaconda/include/qt/QtWidgets/qframe.h \
		../anaconda/include/qt/QtWidgets/QApplication \
		../anaconda/include/qt/QtWidgets/qapplication.h \
		../anaconda/include/qt/QtCore/qcoreapplication.h \
		../anaconda/include/qt/QtCore/qeventloop.h \
		../anaconda/include/qt/QtWidgets/qdesktopwidget.h \
		../anaconda/include/qt/QtGui/qguiapplication.h \
		../anaconda/include/qt/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../anaconda/include/qt/QtWidgets/QMainWindow \
		../anaconda/include/qt/QtWidgets/qmainwindow.h \
		../anaconda/include/qt/QtWidgets/qwidget.h \
		../anaconda/include/qt/QtGui/qwindowdefs.h \
		../anaconda/include/qt/QtCore/qglobal.h \
		../anaconda/include/qt/QtCore/qconfig.h \
		../anaconda/include/qt/QtCore/qfeatures.h \
		../anaconda/include/qt/QtCore/qsystemdetection.h \
		../anaconda/include/qt/QtCore/qprocessordetection.h \
		../anaconda/include/qt/QtCore/qcompilerdetection.h \
		../anaconda/include/qt/QtCore/qtypeinfo.h \
		../anaconda/include/qt/QtCore/qtypetraits.h \
		../anaconda/include/qt/QtCore/qisenum.h \
		../anaconda/include/qt/QtCore/qsysinfo.h \
		../anaconda/include/qt/QtCore/qlogging.h \
		../anaconda/include/qt/QtCore/qflags.h \
		../anaconda/include/qt/QtCore/qatomic.h \
		../anaconda/include/qt/QtCore/qbasicatomic.h \
		../anaconda/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda/include/qt/QtCore/qgenericatomic.h \
		../anaconda/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda/include/qt/QtCore/qatomic_gcc.h \
		../anaconda/include/qt/QtCore/qatomic_msvc.h \
		../anaconda/include/qt/QtCore/qatomic_armv7.h \
		../anaconda/include/qt/QtCore/qatomic_armv6.h \
		../anaconda/include/qt/QtCore/qatomic_armv5.h \
		../anaconda/include/qt/QtCore/qatomic_ia64.h \
		../anaconda/include/qt/QtCore/qatomic_x86.h \
		../anaconda/include/qt/QtCore/qatomic_unix.h \
		../anaconda/include/qt/QtCore/qglobalstatic.h \
		../anaconda/include/qt/QtCore/qmutex.h \
		../anaconda/include/qt/QtCore/qnumeric.h \
		../anaconda/include/qt/QtCore/qversiontagging.h \
		../anaconda/include/qt/QtCore/qobjectdefs.h \
		../anaconda/include/qt/QtCore/qnamespace.h \
		../anaconda/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda/include/qt/QtCore/qobject.h \
		../anaconda/include/qt/QtCore/qstring.h \
		../anaconda/include/qt/QtCore/qchar.h \
		../anaconda/include/qt/QtCore/qbytearray.h \
		../anaconda/include/qt/QtCore/qrefcount.h \
		../anaconda/include/qt/QtCore/qarraydata.h \
		../anaconda/include/qt/QtCore/qstringbuilder.h \
		../anaconda/include/qt/QtCore/qlist.h \
		../anaconda/include/qt/QtCore/qalgorithms.h \
		../anaconda/include/qt/QtCore/qiterator.h \
		../anaconda/include/qt/QtCore/qhashfunctions.h \
		../anaconda/include/qt/QtCore/qpair.h \
		../anaconda/include/qt/QtCore/qbytearraylist.h \
		../anaconda/include/qt/QtCore/qstringlist.h \
		../anaconda/include/qt/QtCore/qregexp.h \
		../anaconda/include/qt/QtCore/qstringmatcher.h \
		../anaconda/include/qt/QtCore/qcoreevent.h \
		../anaconda/include/qt/QtCore/qscopedpointer.h \
		../anaconda/include/qt/QtCore/qmetatype.h \
		../anaconda/include/qt/QtCore/qvarlengtharray.h \
		../anaconda/include/qt/QtCore/qcontainerfwd.h \
		../anaconda/include/qt/QtCore/qobject_impl.h \
		../anaconda/include/qt/QtCore/qmargins.h \
		../anaconda/include/qt/QtGui/qpaintdevice.h \
		../anaconda/include/qt/QtCore/qrect.h \
		../anaconda/include/qt/QtCore/qsize.h \
		../anaconda/include/qt/QtCore/qpoint.h \
		../anaconda/include/qt/QtGui/qpalette.h \
		../anaconda/include/qt/QtGui/qcolor.h \
		../anaconda/include/qt/QtGui/qrgb.h \
		../anaconda/include/qt/QtGui/qrgba64.h \
		../anaconda/include/qt/QtGui/qbrush.h \
		../anaconda/include/qt/QtCore/qvector.h \
		../anaconda/include/qt/QtGui/qmatrix.h \
		../anaconda/include/qt/QtGui/qpolygon.h \
		../anaconda/include/qt/QtGui/qregion.h \
		../anaconda/include/qt/QtCore/qdatastream.h \
		../anaconda/include/qt/QtCore/qiodevice.h \
		../anaconda/include/qt/QtCore/qline.h \
		../anaconda/include/qt/QtGui/qtransform.h \
		../anaconda/include/qt/QtGui/qpainterpath.h \
		../anaconda/include/qt/QtGui/qimage.h \
		../anaconda/include/qt/QtGui/qpixelformat.h \
		../anaconda/include/qt/QtGui/qpixmap.h \
		../anaconda/include/qt/QtCore/qsharedpointer.h \
		../anaconda/include/qt/QtCore/qshareddata.h \
		../anaconda/include/qt/QtCore/qhash.h \
		../anaconda/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda/include/qt/QtGui/qfont.h \
		../anaconda/include/qt/QtGui/qfontmetrics.h \
		../anaconda/include/qt/QtGui/qfontinfo.h \
		../anaconda/include/qt/QtWidgets/qsizepolicy.h \
		../anaconda/include/qt/QtGui/qcursor.h \
		../anaconda/include/qt/QtGui/qkeysequence.h \
		../anaconda/include/qt/QtGui/qevent.h \
		../anaconda/include/qt/QtCore/qvariant.h \
		../anaconda/include/qt/QtCore/qmap.h \
		../anaconda/include/qt/QtCore/qdebug.h \
		../anaconda/include/qt/QtCore/qtextstream.h \
		../anaconda/include/qt/QtCore/qlocale.h \
		../anaconda/include/qt/QtCore/qset.h \
		../anaconda/include/qt/QtCore/qcontiguouscache.h \
		../anaconda/include/qt/QtCore/qurl.h \
		../anaconda/include/qt/QtCore/qurlquery.h \
		../anaconda/include/qt/QtCore/qfile.h \
		../anaconda/include/qt/QtCore/qfiledevice.h \
		../anaconda/include/qt/QtGui/qvector2d.h \
		../anaconda/include/qt/QtGui/qtouchdevice.h \
		../anaconda/include/qt/QtWidgets/qtabwidget.h \
		../anaconda/include/qt/QtGui/qicon.h \
		../anaconda/include/qt/QtMultimedia/QMediaPlayer \
		../anaconda/include/qt/QtMultimedia/qmediaplayer.h \
		../anaconda/include/qt/QtMultimedia/qmediaobject.h \
		../anaconda/include/qt/QtMultimedia/qtmultimediadefs.h \
		../anaconda/include/qt/QtMultimedia/qmultimedia.h \
		../anaconda/include/qt/QtMultimedia/qmediacontent.h \
		../anaconda/include/qt/QtMultimedia/qmediaresource.h \
		../anaconda/include/qt/QtNetwork/qnetworkrequest.h \
		../anaconda/include/qt/QtCore/QSharedDataPointer \
		../anaconda/include/qt/QtCore/QString \
		../anaconda/include/qt/QtCore/QUrl \
		../anaconda/include/qt/QtCore/QVariant \
		../anaconda/include/qt/QtMultimedia/qmediaenumdebug.h \
		../anaconda/include/qt/QtCore/qmetaobject.h \
		../anaconda/include/qt/QtMultimedia/qaudio.h \
		../anaconda/include/qt/QtNetwork/qnetworkconfiguration.h \
		../anaconda/include/qt/QtWidgets/QProgressBar \
		../anaconda/include/qt/QtWidgets/qprogressbar.h \
		../anaconda/include/qt/QtWidgets/qframe.h \
		ui_mainwindow.h \
		../anaconda/include/qt/QtWidgets/QAction \
		../anaconda/include/qt/QtWidgets/qaction.h \
		../anaconda/include/qt/QtWidgets/qactiongroup.h \
		../anaconda/include/qt/QtWidgets/QApplication \
		../anaconda/include/qt/QtWidgets/qapplication.h \
		../anaconda/include/qt/QtCore/qcoreapplication.h \
		../anaconda/include/qt/QtCore/qeventloop.h \
		../anaconda/include/qt/QtWidgets/qdesktopwidget.h \
		../anaconda/include/qt/QtGui/qguiapplication.h \
		../anaconda/include/qt/QtGui/qinputmethod.h \
		../anaconda/include/qt/QtWidgets/QButtonGroup \
		../anaconda/include/qt/QtWidgets/qbuttongroup.h \
		../anaconda/include/qt/QtWidgets/QHeaderView \
		../anaconda/include/qt/QtWidgets/qheaderview.h \
		../anaconda/include/qt/QtWidgets/qabstractitemview.h \
		../anaconda/include/qt/QtWidgets/qabstractscrollarea.h \
		../anaconda/include/qt/QtCore/qabstractitemmodel.h \
		../anaconda/include/qt/QtCore/qitemselectionmodel.h \
		../anaconda/include/qt/QtWidgets/qabstractitemdelegate.h \
		../anaconda/include/qt/QtWidgets/qstyleoption.h \
		../anaconda/include/qt/QtWidgets/qabstractspinbox.h \
		../anaconda/include/qt/QtGui/qvalidator.h \
		../anaconda/include/qt/QtCore/qregularexpression.h \
		../anaconda/include/qt/QtWidgets/qslider.h \
		../anaconda/include/qt/QtWidgets/qabstractslider.h \
		../anaconda/include/qt/QtWidgets/qstyle.h \
		../anaconda/include/qt/QtWidgets/qtabbar.h \
		../anaconda/include/qt/QtWidgets/qrubberband.h \
		../anaconda/include/qt/QtWidgets/QLabel \
		../anaconda/include/qt/QtWidgets/qlabel.h \
		../anaconda/include/qt/QtWidgets/QPushButton \
		../anaconda/include/qt/QtWidgets/qpushbutton.h \
		../anaconda/include/qt/QtWidgets/qabstractbutton.h \
		../anaconda/include/qt/QtWidgets/QStatusBar \
		../anaconda/include/qt/QtWidgets/qstatusbar.h \
		../anaconda/include/qt/QtWidgets/QTextEdit \
		../anaconda/include/qt/QtWidgets/qtextedit.h \
		../anaconda/include/qt/QtGui/qtextdocument.h \
		../anaconda/include/qt/QtGui/qtextoption.h \
		../anaconda/include/qt/QtGui/qtextcursor.h \
		../anaconda/include/qt/QtGui/qtextformat.h \
		../anaconda/include/qt/QtGui/qpen.h \
		../anaconda/include/qt/QtWidgets/QToolBar \
		../anaconda/include/qt/QtWidgets/qtoolbar.h \
		../anaconda/include/qt/QtWidgets/QWidget \
		../anaconda/include/qt/QtCore/QTime \
		../anaconda/include/qt/QtCore/qdatetime.h \
		../anaconda/include/qt/QtGui/QPixmap
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_buttons.o: qrc_buttons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_buttons.o qrc_buttons.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

qrc_sounds.o: qrc_sounds.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_sounds.o qrc_sounds.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

